### ISSUE TITLE
Issue accessing dataset (error)

### ISSUE THREAD

**Issue by SidPad03** [youdescribe-sfsu/You-Described-We-Archived#1]
Followed the given steps in run instructions, encountered this issue. Using Python3.9.

Traceback (most recent call last):
  File "/Users/sidpadmanabhuni/Documents/PyCharmProjects/You-Described-We-Archived/venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sidpadmanabhuni/Documents/PyCharmProjects/You-Described-We-Archived/download_yd_data.py", line 274, in <module>
    main()
  File "/Users/sidpadmanabhuni/Documents/PyCharmProjects/You-Described-We-Archived/download_yd_data.py", line 163, in main
    print(response.json())
  File "/Users/sidpadmanabhuni/Documents/PyCharmProjects/You-Described-We-Archived/venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ManaliSeth** [comment]
I'm sorry that the code wasn't working for you. We have made the required changes and it should be working now as expected. Please try again and let us know if you still face any errors while running the download_yd_data.py script.
